version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bedrock-agentcore-lambda"
s3_prefix = "bedrock-agentcore-lambda"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" AgentRuntimeArn=\"\" SESEmailBucketName=\"\" SQSQueueArn=\"\""
confirm_changeset = true
resolve_s3 = true

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "bedrock-agentcore-lambda-dev"
s3_prefix = "bedrock-agentcore-lambda-dev"
region = "us-west-2"
parameter_overrides = "Environment=\"dev\" AgentRuntimeArn=\"\" SESEmailBucketName=\"\" SQSQueueArn=\"\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[qa]
[qa.deploy]
[qa.deploy.parameters]
stack_name = "bedrock-agentcore-lambda-qa"
s3_prefix = "bedrock-agentcore-lambda-qa"
region = "us-west-2"
parameter_overrides = "Environment=\"qa\" AgentRuntimeArn=\"\" SESEmailBucketName=\"\" SQSQueueArn=\"\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "bedrock-agentcore-lambda-staging"
s3_prefix = "bedrock-agentcore-lambda-staging"
region = "us-west-2"
parameter_overrides = "Environment=\"staging\" AgentRuntimeArn=\"\" SESEmailBucketName=\"\" SQSQueueArn=\"\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "bedrock-agentcore-lambda-prod"
s3_prefix = "bedrock-agentcore-lambda-prod"
region = "us-west-2"
parameter_overrides = "Environment=\"prod\" AgentRuntimeArn=\"\" SESEmailBucketName=\"\" SQSQueueArn=\"\""
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
